sudo: required
services:
  - docker

before_install:
  - docker build -t segyhp/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker -e CI=true run segyhp/react-test npm test -- --coverage
after_success:
  - docker build -t segyhp/complex-client ./client
  - docker build -t segyhp/complex-server ./server
  - docker build -t segyhp/complex-nginx ./nginx
  - docker build -t segyhp/complex-worker ./worker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-std-in
  #Push images to Docker Hub
  - docker push segyhp/multi-client
  - docker push segyhp/multi-server
  - docker push segyhp/multi-nginx
  - docker push segyhp/multi-worker
